# Generated by Django 4.0.5 on 2022-06-24 07:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nanny_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profilepic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile'),
        ),
    ]
